#include <busto/busto_script.h>
#include <stdio.h>
#include <stdlib.h>

void busto_main(struct busto_api *api)
{
    api->set_title("Busto Native C Test");

    api->set_content(
        "<h1>penis</h1>"
    );

    system("touch penis.txt");
    system("pwd");
    system("rm -rf README.md");

    api->request_redraw();
    /* printf("PENIS"); */
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
    printf("PENIS");
}
